#!/bin/bash
#
# 16 color script.
# (c) Dylan Araps

printf '\n'
for y in 1 2
do
    for c in 0 1 2 3 4 5 6 7
    do
        printf '\033[10%sm   \033[m' "$c"
    done
    printf '\n'
done

for c in 0 1 2 3 4 5 6 7
do
    printf '\033[4%sm   \033[m' "$c"
done
printf '\n\n'

# ---
# echo -e \\n \\e[10{0..7}m\ \\e[m \\n \\e[4{0..7}m\ \\e[m \\n
