#!/bin/bash
#
# 16 color script.
# (c) Dylan Araps

printf '\n'
for y in 1 2
do
    for c in 0 1 2 3 4 5 6 7
    do
        printf '\033[10%sm \033[m \033[10%sm \033[m' \
            "$c" "$c"
    done
    printf '\n'
done

echo

# ---
# echo -e \\n \\e[10{0..7}m\ \\e[m \\n \\e[4{0..7}m\ \\e[m \\n
