#!/bin/sh
#
# 2pow - list powers of 2 
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {
	x=0
	while true; do 
		printf "2^${x} : %s\n" "$(echo "2^${x}" | bc)"
		x=$(($x+1))
	done
}

main "$@"

