#!/bin/mksh
#
# vim: filetype=bash
#
# archive-image: archive a tumblr (and soon, reddit/unsplash/twitter) image post
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

setexif() {
	blog=$1
	content_text=$2
	content_surl=$3
	content_tags=$4
	archive_date=$5
	filename=$6
	echo $filename

	# This needs to be UCS2 encoded...
	#exiftool -XPTitle="$content_summary" $filename
	#exiftool -XPAuthor=$blog $filename
	#exiftool -XPKeywords="$content_tags" $filename

	exiftool -Artist=$blog $filename
	exiftool -ImageDescription="$content_text" $filename
	exiftool -ImageSourceData="$content_surl" $filename
	exiftool -UserComment="$content_tags" $filename
	exiftool -DateTime="$archive_date" $filename
}

set -e
. $(which std)

T_HELPER=$HOME/bin/lib/tumbler_helper.py
ARCHIVE_DIR=$HOME/arc/art/

if [ "$1" = "" ]
then
	die "usage: $0 <url>"
fi

url=$1

if grep -q 'tumblr' <<< "$url"
then
	IFS='/' read _ blog id <<< $(grep -oEi 'tumblr\.com/[a-zA-Z0-9_\-]+/[0-9]+' <<< "$url")
	printf 'Archiving %d from %s\n' "$id" "$blog"

	consumer_key="AFVyAQ9OS7urVp57OtpufMcQJK3pGlV4NcslhXORnK5kBzvt2F"
	consumer_key_secret="BzPIqaZJAzcjlrMIbkWMjPtCecedFLAhDU7j9XGrabgz8Y2bXv"
	read oauth oauth_secret < $HOME/.ssh/tumblr.secrets

	response=$(python3 $T_HELPER $consumer_key $consumer_key_secret $oauth $oauth_secret $blog $id)

	content_image=$(printf '%s' "$response" | \
		jq '.content | .[] | .media | .[0] | select(.url != null) | .url' | \
		tr -d '"' | tr '\n' ' ')
	content_text=$(printf '%s' "$response" | \
		jq '.content | .[] | .text | select(. != null)' | \
		tr -d '"')
	content_slug=$(printf '%s' "$response" | jq '.slug' | tr -d '"')
	content_surl=$(printf '%s' "$response" | jq '.short_url' | tr -d '"')
	content_summ=$(printf '%s' "$response" | jq '.summary' | tr -d '"')
	content_tags=$(printf '%s' "$response" | jq '.tags | .[]' | tr -d '"' | tr '\n' ' ')

	read -r main_tag_guess _ <<< "$content_tags"

	filelist=""
	ext="png"
	ctr=0
	for i in $content_image
	do
		rm -f /tmp/archive-image-tmp-file
		wget $i -O /tmp/archive-image-tmp-file
		IPA=" ," read -r _ ext <<< $(file --extension /tmp/archive-image-tmp-file)
		ctr=$((ctr+1))
		filename="/tmp/tumblr-$id-${ctr}.${ext}"
		filelist="$filelist ${filename}"
		mv /tmp/archive-image-tmp-file $filename
	done

	if [ "$ext" == "gif" ] && [ "$ctr" -gt 1 ]
	then
		ctr2=0
		for i in $filelist
		do
			setexif "$blog" "$content_text" "$content_surl" "$content_tags" "$(date +%Y-%m-%d)" $i
			mv $i "${ARCHIVE_DIR}/${content_slug}-${ctr2}.${ext}"
			ctr2=$((ctr2+1))
		done
	else
		filename=/tmp/tumblr-$id-combined.${ext}
		rm -f $filename
		if [ $ctr -gt 1 ]
		then
			convert -append $filelist $filename
		else
			mv $filelist $filename
		fi
		rm -f $filelist

		setexif "$blog" "$content_text" "$content_surl" "$content_tags" "$(date +%Y-%m-%d)" $filename
		mv $filename "${ARCHIVE_DIR}/${content_slug}.${ext}"
	fi
elif grep -q 'reddit' <<< "$url"
then
	die "Reddit archival unimplemented"
fi
