#!/bin/sh
#
# bar - the holy polybar
# (c) Kiëd Llaentenn

get_dwminfo() {
	mode=$(cat /tmp/dwm_info/current_layout)
	case $mode in
		"0") echo "[]=" ;;
		"1") echo "><>" ;;
		"2") echo "[M]" ;;
		"3") echo "(@)" ;;
		"4") echo "[\]" ;;
	esac
}

main() {
	killall polybar
	exec polybar bar
}

main "$@"
