#!/usr/bin/env bash
#
# bar - simple bar script based on polybar>lemonbar

main() {
	. ${HOME}/.cache/wal/colors.sh
	~/.config/polybar/launch-dwm.sh | lemonbar \
		-g 1896x24+12+1048 \
		-f "Siji:size=9" -f "xos Terminus:size=9" \
		-n bar \
		-pdb  -u 3 \
		-B $color0 -F $color7 # accent color: $color6
}

main "$@"
