#!/bin/sh
#
# calc - interactive wrapper for bc
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {
	while true; do
		printf "\033[1;32m❯❯ \033[1;37m"
		read -r calc
		printf "\033[0m"
		case calc in
			exit*) printf "\033[0m\n" && exit ;;
			clear*) clear ;;
			*) echo "${calc}" | bc -ql ;;
		esac
	done
}

trap "printf \"\033[0m\n\" && exit" INT
main "$@"
