#!/bin/sh
#
# clean - remove orphaned packages and clean cache directory
# (c) Kied Llaentenn (@kiedtl)
# See the COPYING for more information.

find ~ -maxdepth 1 -type f -name '*history' -print0 | \
    xargs -0 rm -f

if has xbps-remove >/dev/null 2>&1; then
    xbps-remove -o
    rm -rf /var/cache/xbps/*
fi

[ -d ~/.cargo ] && rm -rf ~/.cargo/*
[ -d ~/go ] && {
    for junk in $(find ~/go/pkg/* ~/go/src/*); do
        chmod 700 "$junk"
        rm -f "$junk" >&2 2>/dev/null
    done
}
[ -d ~/tmp ] && rm -rf ~/tmp/*
[ -d ~/Downloads ] && rm -rf ~/Downloads
