# Shell variables
# Generated by 'wal'
wallpaper='/home/kiedtl/wallpapers/landscape-013.jpg'

# Special
background='#0d0b07'
foreground='#c4c5c5'
cursor='#c4c5c5'

# Colors
color0='#0d0b07'
color1='#4E4D4E'
color2='#696866'
color3='#897745'
color4='#9C903D'
color5='#A5925F'
color6='#79808C'
color7='#c4c5c5'
color8='#898989'
color9='#4E4D4E'
color10='#696866'
color11='#897745'
color12='#9C903D'
color13='#A5925F'
color14='#79808C'
color15='#c4c5c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
