#!/bin/sh
#
# colors - dump pywal colorscheme
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING for copyright information.

[ -f "$HOME/.cache/wal/colors" ] || \
    exit 1

cat $HOME/.cache/wal/colors | \
    tr '\n' ' '

printf '\n'
