#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# return dns server with lowest ping
#

servers="\
1.1.1.1
1.0.0.1
4.2.2.1
4.2.2.2
8.8.8.8
8.4.4.8
9.9.9.9
8.26.56.26
8.20.247.30
75.75.75.75
75.75.76.76
"

lowest_time=9999
lowest_dns=""

for i in $servers ; do
    time=$(ping -c 1 -s 16 -w 1 -n $i)
    [ $? -gt 0 ] && continue

    time=$(echo $time | grep -oE '[0-9]+(\.[0-9]+)?( )?ms' | \
            head -n 1 | sed -E -e 's/ms//' -e 's/\.[0-9]+//')

    if [ $time -lt $lowest_time ] ; then
        lowest_time=$time
        lowest_dns=$i
    fi
done

echo $lowest_dns
