#!/bin/sh
#
# ed - open file in editor.
# (c) Kied Llaentenn (@kiedtl)
# See the COPYING for more information.

. $(which std)

[ -d "$1" ] && die 'cannot edit directory'

[ ! -f "$1" ] && {
    printf "ed: \"${1}\" doesn't exist -- create? [yN] ";
    read ans;

    case "$ans" in
        [Yy]*) touch "$1" ;;
        *)     exit 1     ;;
    esac
}

ed="${EDITOR:-nvim}"
has $ed || ed="vim --clean"
has $ed || ed="vi"

[ -f "$1" ] && exec $ed "$@"
