#!/bin/sh
#
# ed - open file in editor.
# (c) Kied Llaentenn (@kiedtl)
# See the COPYING for more information.

[ -d "$1" ] && {
    printf "ed: cannot edit directory!!\n";
    exit 1;
}

[ ! -f "$1" ] && {
    printf "ed: \"${1}\" doesn't exist -- create? [yN] ";
    read ans;

    case "$ans" in
        [Yy]*) touch "$1" ;;
        *) ;;
    esac
}

[ -f "$1" ] && "$EDITOR" "$@"
