#!/bin/sh
#
# esc - swap CAPS LOCK and Escape
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

command -v xmodmap >/dev/null 2>&1 || exit 1

xmodmap -e "clear lock"
xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
xmodmap -e "keycode 66 = Escape NoSymbol Escape"
