#!/bin/sh
#
# extract - an all-purpose file archive extractor
# from Manjaro Linux

[ -z "${1}" ] && exit 1

if [ -f $1 ] ; then
    case $1 in
        *.tar.xz)     tar xvf $1     ;;
        *.tar.bz2)    tar xjf $1     ;;
        *.tar.gz)     tar xzf $1     ;;
        *.bz2)        bunzip2 $1     ;;
        *.rar)        unrar x $1     ;;
        *.gz)         gunzip $1      ;;
        *.tar)        tar xf $1      ;;
        *.tbz2)       tar xjf $1     ;;
        *.tgz)        tar xzf $1     ;;
        *.zip)        unzip $1       ;;
        *.Z)          uncompress $1  ;;
        *.7z)         7z x $1        ;;
        *)            echo "'$1' cannot be extracted!" ;;
    esac
else
    echo "'$1' does not exist"
fi
