#!/bin/sh
#
# fetch - rsfetch wrapper
# (c) Kiëd Llaentenn
# see the LICENSE for more information.

reset=$(printf "\033[0m")
bold=$(printf "\033[1m")
data=

while IFS="\n" read -r info; do
	data="${data} $info"
done <<EOF
$(rsfetch -deskM)
EOF

set -- ${data}

echo "
${bold} |\___/|   os ${reset}> ${1}
${bold} /     \   ke ${reset}> ${2}
${bold}/__^ ^__\  ed ${reset}> ${3}
${bold}   \o/     sh ${reset}> ${4}
"
