#!/bin/sh
#
# fetch - rsfetch wrapper
# (c) Kiëd Llaentenn

# color escapes
BLK="$(printf "\033[30m")"
RED="$(printf "\033[31m")"
GRN="$(printf "\033[32m")"
YLW="$(printf "\033[33m")"
BLU="$(printf "\033[34m")"
PUR="$(printf "\033[35m")"
CYN="$(printf "\033[36m")"
WHT="$(printf "\033[37m")"
RST="$(printf "\033[0m")"

# build the color bars
BAR="━━━━"
LEN=6
OUTT="$RED$BAR$GRN$BAR$YLW$BAR$BLU$BAR$PUR$BAR$CYN$BAR$RST"

data=

while IFS="\n" read -r info; do
	data="${data} $info"
done <<EOF
$(rsfetch -dskMp xbps)
EOF

set -- ${data}

echo "
${OUTT}
${BLU}os                  ${RST}${1}
${BLU}kernel         ${RST}${2}
${BLU}packages             ${RST}${4}
${BLU}shell              ${RST}${3}
${OUTT}
"
