#!/bin/sh
#
# font - list and preview fonts
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

output=${1}

preview_text=$(echo "
        A B C D E F G H I J K L M 
        N O P Q R S T U V W X Y Z

           1 2 3 4 5 6 7 8 9 0

        a b c d e f g h i j k l m
        n o p q r s t u v w x y z

        () [] {} <> ? / \\ : \" ' ;
        ! @ # $ % ^ & * _ = + - |
                   \` ~")

[ -z "${output}" ] && {
    echo "${preview_text}";
    exit
}

font=$(convert -list font | awk -F: '/^[ ]*Font: /{print substr($NF,2)}' | fzf)

convert -size 532x365 xc:"#ffffff" \
    -gravity center \
    -pointsize 38 \
    -font "${font}" \
    -fill "#000000" \
    -annotate +0+0 \
    "${preview_text}" \
    -flatten "${output}"

feh "${output}"
