#!/bin/sh
#
# gfe - git fetch script
# (c) Kied Llaentenn
# see the LICENSE for more information.
# NOTE: this script contains items stol^Htaken from
# http://github.com/mitchweaver/bin.

# TODO:
#   - name@project name     e.g. "kiedtl@bin"
#   - HEAD                  latest commit sha
#   - created               date of first commit
#   - language              main language of project
#   - contributors          authors (in the format: <percent> <author> <commit count>
#   - last change           how long ago was the last commit?
#   - repo                  URL of master/origin
#   - commit                commit count
#   - lines of code         number of the lines of code
#   - size kB (file count)  size of all files not ignored by git
#   - license               e.g. MIT
#   - language spread       like the language colors on GitHub

get_name() {
    echo "$USER"
}

get_project_name() {
    basename $(pwd)
}

get_head() {
    git log -1 --format="%h"
}

get_created() {
    git log --reverse --format="%ar" | head -n1
}


main() {
    printf "\033[1mCommits\n\033[0m"
    git rev-list --count --all
    printf "\n\033[1mContributors\n\033[0m"
    git log --format="%aN"| \
        sort | \
        uniq -c | \
        sort -nr | \
        sed 's|^[ ]*[^ ]*[ ]*||'
}

main "$@"
