#!/bin/sh
#
# gfe - git fetch script
# (c) Kied Llaentenn
# see the LICENSE for more information.
# NOTE: this script contains items stol^Htaken from
# http://github.com/mitchweaver/bin.

main() {
    printf "\033[1mCommits\n\033[0m"
    git rev-list --count --all
    printf "\n\033[1mContributors\n\033[0m"
    git log --format="%aN"| \
        sort | \
        uniq -c | \
        sort -nr | \
        sed 's|^[ ]*[^ ]*[ ]*||'
}

main "$@"
