#!/bin/sh
#
# gupd - git: update file
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

. $(which std)

file="$1"
shift

git add "$file" || die "git add failed"
git commit -m "$file: ${@:-update}" || die "git commit failed"
