#!/bin/sh
#
# init - initialize a C project
# (c) Kiëd Llaentenn (@kiedtl)
# See the LICENSE for more information.

name=${1}
desc=${2}

[ -z "${name}" ] && read -r name
[ -z "${desc}" ] && read -r desc

# create directory
mkdir -vp "${name}"
cd "${name}"

# initialize git
git init

# create README
printf "# ${name}

> ${desc}

## what?

## how?

## where?

## why?

## known issues

## license
- This project is licensed under the MIT license. [View LICENSE.md](LICENSE.md)
" > README.md

# create .gitignore
printf "# ignore Vim's swap files
**/*.*.swp

# ignore object files
**/*.o
${name}
" > .gitignore

# create LICENSE
printf "### MIT License

> Copyright © 2019 Kiëd Llaentenn

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights to
(mis)use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is furnished
to do so, subject to the following conditions:

- The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**this software is provided \"as is\", without warranty of any kind, express or
implied, including but not limited to the warranties of merchantability,
fitness for a particular purpose and noninfringement. in no event shall the
authors or copyright holders be liable for any claim, damages or other
liability, whether in an action of contract, tort or otherwise, arising from,
out of or in connection with the software or the use or other dealings in
the software.**
" > LICENSE.md

# create makefile
printf "#
# ${name}: ${desc}
# (c) Kiëd Llaentenn
# See the LICENSE for more information
#

NAME    = ${name}
WARNING = -Wall -Wextra -pedantic -Wmissing-prototypes \
          -Wold-style-definition -Werror -Wno-unused-parameter

INC     = -I. -Isub/ccommon/

CC      = gcc
CFLAGS  = -std=c99 $(WARNING) $(INC) -ggdb -fno-stack-protector
LDFLAGS = -fuse-ld=gold

SRC     = \$(NAME).c
OBJ     = \$(SRC:.c=.o)

DESTDIR = /
PREFIX  = /usr/local/

all: \$(NAME)

clean:
        rm -f \$(NAME) \$(OBJ)

.c.o:
        @echo \"CC        \$@\"
        @\$(CC) \$(CFLAGS) -c $<

\$(NAME): \$(OBJ)
        @echo \"LD        \$(NAME)\"
        @\$(CC) -o \$@ \$^ \$(CFLAGS) \$(LDFLAGS)

install: \$(NAME)
        @echo \"INSTALL  \$(NAME)    \$(DESTDIR)/\$(PREFIX)/bin/\$(NAME)\"
        @install -m755 ./\$(NAME) \$(DESTDIR)/\$(PREFIX)/bin/\$(NAME)

uninstall:
        @echo "RM        \$(DESTDIR)/\$(PREFIX)/bin/\$(NAME)"
        @rm -f \$(DESTDIR)/\$(PREFIX)/bin/\$(NAME)

.PHONY: all clean install
" > makefile

# create skeleton
printf "#include \"${name}.h\"\n" > "${name}.c"
printf "#ifndef $(echo "${name}" | sed 's/\(.*\)/\U\1/')_H
#define $(echo "${name}" | sed 's/\(.*\)/\U\1/')_H

#endif
" > "${name}.h"
