#!/bin/sh
image=$(printf "\033[48;5;1m\033[38;5;0m\033[1m")
label=$(printf "\033[0m\033[48;5;0m\033[38;5;1m")
reset=$(printf "\033[0m")
. /etc/os-release;k=`uname -r`;s=`cat /proc/uptime`;s=${s%%.*};d=$((s/86400));h=$((s/3600%24));m=$((s/60%60));[ $d = 0 ]||u="${u}${d}d ";[ $h = 0 ]||u="${u}${h}h ";[ $m = 0 ]||u="${u}${m}m";while IFS=: read -r a b;do b=${b%kB};case $a in MemTotal)x=$((x+=b));t=$((t=b));;Shmem)x=$((x+=b));;MemFree|Buffers|Cached|SReclaimable)x=$((x-=b));;esac;done</proc/meminfo;x=$((x/=1024));t=$((t/=1024))

echo "
${image}       ___      ${label}  USER    ${reset}${USER}@`hostname`
${image}      (.· |     ${label}  OS      ${reset}${PRETTY_NAME:-?}
${image}      (<> |     ${label}  UPTIME  ${reset}$u
${image}     / __  \    ${label}  EDITOR  ${reset}${EDITOR:-?}
${image}    ( /  \ /|   ${label}  SHELL   ${reset}${SHELL##*/}
${image}   _/\ __)/_)   ${label}  MEMORY  ${reset}${x}MiB / ${t}MiB
${image}   \/-____\/    ${label}  KERNEL  ${reset}$k
${image}                ${label}  PKGS    ${reset}`xbps-query -l | wc -l`
">/dev/null

echo "
${image}                ${label}  USER    ${reset}${USER}@`hostname`
${image}                ${label}  OS      ${reset}${PRETTY_NAME:-?}
${image}     (\(\       ${label}  UPTIME  ${reset}$u
${image}     ( . ·)     ${label}  EDITOR  ${reset}${EDITOR:-?}
${image}     c(\")(\")    ${label}  SHELL   ${reset}${SHELL##*/}
${image}                ${label}  MEMORY  ${reset}${x}MiB / ${t}MiB
${image}                ${label}  KERNEL  ${reset}$k
                  ${label}PKGS    ${reset}`xbps-query -l | wc -l`"
