#!/bin/sh
#
# simple-colored - simple, colored.
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

br="$(printf '\033[1;33m')"
re="$(printf '\033[0m')"
bo="$(printf '\033[1m')"

echo "
${br}${USER}${re}@${br}$(hostname)${re}
${br}  ${re}$(os)
${br}  ${re}$(uname -r)
${br}  ${re}$(upt)
${br}  ${re}$(pkgs '$pkgs_total')
${br}  ${re}$(wm)
${br}  ${re}${SHELL##*/}
${br}  ${re}xterm
${br}  ${re}$(interface)
${br}  ${re}$(disk)
${br}  ${re}$(mem)
" 2>/dev/null
