#!/bin/sh
#
# lbar: the unholy lemonbar
# credits: u/z-brah

bg=$(xrdb -query | grep "*.foreground" | awk '{ print $2 }') #00ffffff
fg=$(xrdb -query | grep "*.background" | awk '{ print $2 }') #ff666b7d
ac=$(xrdb -query | grep "*.color2:" | awk '{ print $2 }')

tfg1="${bg}"
bg="#00${bg#\#}"
fg="#ff${fg#\#}"

fn='cozette'

clock() {
    echo "$(date '+%a %d') %{R}%{F$tfg1} $(date +%H:%M) %{F$bg}%{R}"
}

wifi() {
    if=$(interface)
    rfkill="$(LC_ALL=C rfkill -r | grep wlan | cut -d ' ' -f 4)"
    [ "$rfkill" = "blocked" ] && return
    ssid=$(iwgetid -r $if)
    echo "ssid %{R}%{F$tfg1} ${ssid:--} %{F$bg}%{R}"
}

diskavail() {
    avail=$(df -h | grep /dev/root | awk '{ print $4 }')
    echo "disk %{R}%{F$tfg1} ${avail:--} %{F$bg}%{R}"
}

memory() {
    while IFS=: read -r a b
    do
        b=${b%kB}

        case $a in
            MemTotal) x=$((x+=b)) ;;
            Shmem) x=$((x+=b)) ;;
            MemFree|Buffers|Cached|SReclaimable) x=$((x-=b)) ;;
        esac
    done </proc/meminfo
    x=$((x/=1024))

    echo "mem %{R}%{F$tfg1} ${x:--} MiB %{F$bg}%{R}"
}

while sleep 1; do
    printf '%%{c} %s %s %s %s %s\n' \
        "$(clock)" \
        "$(wifi)" \
        "$(diskavail)" \
        "$(memory)"
done | lemonbar  -dB "$bg" -F "$fg" -f "$fn" -g 1920x32+0+0
