#!/bin/sh
#
# lbar: the unholy lemonbar
# credits: u/z-brah

bg=$(xrdb -query | grep "*.color1" | awk '{ print $2 }') #00ffffff
fg=$(xrdb -query | grep "*.background" | awk '{ print $2 }') #ff666b7d
ac=$(xrdb -query | grep "*.color2:" | awk '{ print $2 }')

tfg1="${bg}"
bg="#ff${bg#\#}"
fg="#ff${fg#\#}"

fn='ttyp0'

clock() {
    echo "$(date '+%a %d') $(date +%H:%M)"
}

name() {
    nm="$(xdotool getwindowfocus getwindowname)"
    case $nm in
        Awesome*) printf '\n' ;;
        *) printf '%s' "$nm" ;;
    esac
}

wifi() {
    if=$(interface)
    rfkill="$(LC_ALL=C rfkill -r | grep wlan | cut -d ' ' -f 4)"
    [ "$rfkill" = "blocked" ] && return
    ssid=$(iwgetid -r $if)
    echo "${ssid:--}"
}

diskavail() {
    avail=$(df -h | grep /dev/root | awk '{ print $4 }')
    echo "${avail:--}"
}

memory() {
    while IFS=: read -r a b
    do
        b=${b%kB}

        case $a in
            MemTotal) x=$((x+=b)) ;;
            Shmem) x=$((x+=b)) ;;
            MemFree|Buffers|Cached|SReclaimable) x=$((x-=b)) ;;
        esac
    done </proc/meminfo
    x=$((x/=1024))

    echo "${x:--} MiB"
}

while sleep 0.1; do
    printf '%%{l}  %s %%{c} %s %%{r} %s %s %s \n' \
        "$(name)" \
        "$(clock)" \
        "$(memory)" \
        "$(diskavail)"
done | lemonbar  -dB "$bg" -F "$fg" -f "$fn" -g 1920x24+0+0
