#!/usr/bin/env bash
#
# lockscreenset - configure betterlockscreen

mails=$(cat ~/.fehbg | tr " " "\n")
image=""

for addr in $mails
do
    image=$addr
done
image=${image#"'"}
image=${image%"'"}
betterlockscreen -u $image