#!/bin/sh
#
# log - read logs from an IRC channel
# as always, mostly stolen from Dylan Araps
# https://github.com/dylanaraps/bin

log() {
    curl "https://freenode.logbot.info/${1}/${2}/raw" | \
        while read -r _ n m; do
            n=${n%>}
            n=${n#<}

            printf '%12s %s\n' "$n" "$m"
        done
}

log "${1:-kisslinux}" "$(date +%Y%m%d)"
