#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

missing=0

chk() {
    for i ; do
        type $i >/dev/null || {
            >&2 printf '    * %s\n' $i;
            missing="$((missing+1))"
        }
    done
}

printf 'missing:\n'

# basic
chk awk sed grep pgrep file

# rust utils
chk exa fd rg tokei hyperfine dust

# c programming
chk gcc ld.lld make nvim git gdb

# other languages
chk bash mksh tclsh lua

# xorg
chk awesome startx xterm dmenu wal slock polybar lemonbar \
    xsel xmodmap xdotool xsetroot xrdb xprop

# programs
chk mupdf netsurf feh

# networking
chk ssh wpa_supplicant curl wget

# monitoring
chk htop pv

# misc
chk xz bzip2 gzip unzip gpg2 jq

printf '%s not found\n' "$missing"
