#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# verifies if I have all my common programs installed
#

missing=0

chk() {
    for i ; do
        type $i 2>/dev/null >&2 || {
            >&2 printf '    * %s\n' $i;
            missing="$((missing+1))"
        }
    done
}

printf 'missing:\n'

# basic
chk awk sed grep pgrep file less

# rust utils
chk exa fd rg tokei hyperfine dust

# c programming
chk gcc ld.lld make git gdb scdoc patch

# other languages
chk bash mksh tclsh dash cargo

# xorg
if command -v X 2>/dev/null >&2
then
    chk startx xsel xmodmap xdotool xsetroot \
        xrdb xprop xcompmgr xautolock

    # xorg programs
    chk mupdf feh 2bwm xterm dmenu slock polybar \
        lemonbar
fi

# ricing
chk wal paleta

# programs
chk taizen weechat convert nvim

# networking
chk ssh wpa_supplicant curl wget

# monitoring
chk ytop pv htop

# misc
chk xz bzip2 gzip unzip jq gfe lcharmap kjv

printf '%s not found\n' "$missing"
