#!/bin/sh
#
# mkil - 'kill -9 $(ps | dmenu)'
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

cmd='ps -eukiedtl axh -opid,%cpu,%mem,command --sort=-%cpu'
pid=$(ndmen "$cmd" cat | awk '{print $1}')
[ "$pid" ] && herbe "$($(which kill) -9 "$pid" 2>&1 && echo Killed $pid)"
