#!/bin/sh
#
# mks - create a shell script using a template.
# partly stolen from Dylan Arap's dotfiles.

[ -z "$1" ] && exit

echo "#!/bin/sh
#" > "$1"

[ -z "$2" ] || echo "# $1 - $2" >> "$1"

echo "# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

" >> "$1"

chmod +x "$1"
