#!/usr/bin/env bash
#
# Create a bash script using a template.

[[ $1 ]] || exit 1

printf '%s' "\
#!/bin/sh
#
# $1 - $2
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {

}

main \"\$@\"
" > "$1" && chmod +x "$1"
