#!/bin/sh
#
# motd - display motd
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

[ -f /etc/motd ] && motd=/etc/motd
[ -f /var/run/motd ] && motd=/var/run/motd

less /var/run/motd
