#!/bin/sh
#
# netmon [delay] - monitor network
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

tx_path=/sys/class/net/$(interface)/statistics/tx_packets #bytes
rx_path=/sys/class/net/$(interface)/statistics/rx_packets #bytes

while :; do
    sleep "${1:-1}"

    read -r tx_cur < "$tx_path"
    read -r rx_cur < "$rx_path"
    cur=$((rx_cur+tx_cur))

    printf '%s,%s\n' \
        "$(date +%s)" \
        "$(dc -e "$cur ${last:-$cur} - p")"

    last=$cur
done
