#!/bin/sh
rd=`printf "\033[31m\033[1m"`
rs=`printf "\033[0m"`
. /etc/os-release;k=`uname -r`;s=`cat /proc/uptime`;s=${s%%.*};d=$((s/86400));h=$((s/3600%24));m=$((s/60%60));[ $d = 0 ]||u="${u}${d}d ";[ $h = 0 ]||u="${u}${h}h ";[ $m = 0 ]||u="${u}${m}m";while IFS=: read -r a b;do b=${b%kB};case $a in MemTotal)x=$((x+=b));t=$((t=b));;Shmem)x=$((x+=b));;MemFree|Buffers|Cached|SReclaimable)x=$((x-=b));;esac;done</proc/meminfo;x=$((x/=1024));t=$((t/=1024))

echo "
${rd}    ___     ${USER:-`id -nu`}@${HOSTNAME:-`hostname`}
${rd}   (.· |    os      ${rs}${PRETTY_NAME:-?}
${rd}   (<> |    uptime  ${rs}$u
${rd}  / __  \   editor  ${rs}${EDITOR:-?}
${rd} ( /  \ /|  shell   ${rs}${SHELL##*/}
${rd}_/\ __)/_)  memory  ${rs}${x}MiB / ${t}MiB
${rd}\/-____\/   kernel  ${rs}$k
"
