#!/bin/bash
#
# rcmen: menu when right click
# from r/unixporn: "[dwm] plan 9 feel" by u/_viz_
# edited by kiedtl:
# 	- changed hacksaw to crud
#	- BPX/BCOL make static
#	- add clear function
#	- changed crud to xrectsel
# NOTE: requires bash due to use of arrays.

BPX=4
BCOL="#fff"

#read -r BPX < /tmp/info/dwm/borders/size
#read -r BCOL < /tmp/info/dwm/borders/selcol

get_id_interactive() {
    xid=`xwininfo | grep 'Window id: '`
    echo ${xid} | cut -d':' -f3 | cut -d' ' -f2
}

resize() {
    id=`get_id_interactive`
    #eval $(crud)
    read -r W H X Y <<< $(xrectsel '%w %h %x %y')

    xdotool windowsize ${id} ${W} ${H}
    xdotool windowmove ${id} ${X} ${Y}
}

new() {
    fw=5	# width of term font
    fh=11	# height of term font
    ib=12	# size of term inner border
    ob=4	# size of term windows WM border

    #eval $(crud)
    #tabbed -n st -cg "${G}" -r 2 st -w '' -t terminal
   
    read -r W H X Y <<< $(xrectsel '%w %h %x %y') 
    w=$(( ( W - (ib + ob)*2 ) / fw ))
    h=$(( ( H - (ib + ob)*2 ) / fh )) 
    
    xterm -title terminal -geometry "${w}x${h}+${X}+${Y}"
}

delete() {
    id=`get_id_interactive`
    xdotool windowclose ${id}
}

hide() {
    id=`get_id_interactive`
    xdotool windowunmap ${id}
    [ ${?} -eq 0 ] && echo ${id} >> /tmp/dwm_info/hidden
}

scratchpad() {
	w_id=$(xdotool search --name scratchpad)
	xdotool windowmap ${w_id}
}

spawn() {
    eval $(xdotool getmouselocation --shell)
    9menu -font "Fixed" \
          -geometry 100x100+${X}+${Y} -popup                                            \
          'new:echo new' 'launch: echo ndmen' 'resize:echo resize' 'delete: echo delete' 'hide: echo hide' 'show:echo show' 'lock: echo slock'
}

$(spawn)
exit
