#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Records a selected rectangle with ffmpeg.
#

[ $# -eq 0 ] &&
    video_path="${HOME}/vid/captures/record-$(date '+%b_%d-%H:%M')" ||
    video_path=${1}

set -- `xrectsel '%x %y %w %h'`

ffmpeg -y -f x11grab -s ${3}x${4} \
       -r 30 -i ${DISPLAY:=:0.0}+${1},${2}    \
       -vcodec libx264 \
       ${video_path}.mp4
