#!/bin/sh
#
# http://github.com/mitchweaver/bin
#
# Records a selected rectangle with ffmpeg.
#

[ $# -eq 0 ] &&
    video_path="${HOME}/Videos/captures/record-$(date '+%b_%d-%H:%M')" ||
    video_path=${1}

set -- `xrectsel '%x %y %w %h'`

ffmpeg -y -f x11grab -s ${3}x${4} \
       -r 30 -i :1.0+${1},${2}    \
       -pix_fmt yuv420p -qscale 0 \
       ${video_path}.mp4
