#!/bin/bash
#
# rp - recursively get paths in pure shell
# from StackOverflow

main() {
	d=${1}
	for f in "${prefix}/${d}/"*; do
		[ -f "$f" ] && echo "$f"
		[ -d "$f" ] && {
			( cd "$f"; main "$f" "${prefix}/${f}"; );
		}
	done
}

main "$1" "./"

