#!/bin/sh
#
# rwall - random wallpaper
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {
	dir=/tmp/rwall
	mkdir -p $dir
	file="$dir/$$-unsplash-1920x1080.png"
	curl -LC - -o "$file" --url http://source.unsplash.com/random/1920x1080 -- > /dev/null 2>&1
	feh $file
}

main "$@"

