#!/bin/mksh
#
# shtat - primitive shell history statistics
# NOTE: must be sourced to work.
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

shtat() {
    history 0 | \
        awk \
            '{
                commands[$2]+=1
                total+=1
            }

            END {
                for (command in commands) {
                    percentage=(commands[command]*100)/total
                    printf "%s,%s%%,%s\n", commands[command], percentage, command
                }
            }' | \
        while IFS=, read -r count perc cmd; do
            [ "$cmd" = "while" ]   && continue
            [ "$cmd" = "for" ]     && continue
            [ "$cmd" = "if" ]      && continue
            [ "$cmd" = "command" ] && continue
            [ "$cmd" = "exit" ]    && continue

            command -v -- "$cmd" 2>/dev/null >&2 || continue

            grep -q / <<< "$cmd" && cmd="$(command -v -- "$cmd")"
            printf '%-5s %13s    %s\n' "$count" "$perc" "$cmd"
        done | \
        sort -bnr | \
        nl | \
        head -n "${1:-8}"
}
