#!/usr/bin/env bash
#
# ssh - hmmmmmmmm...

prompt=$(printf "+\e[1;32mkiedtl@hell\e[1;34m ~ (master x!?)\e[0m %s" '%')

main() {
    if [[ "$1" == "god@heaven" ]]; then
        echo 'god@heaven: Permission denied (publickey)'
    else
        echo 'Last login: Mon Jun 12 09:12:33 @ exams'
        printf '%s exit\n' "$prompt"
        echo 'Connection to hell closed.'
    fi
}

main "$@"
