#!/bin/sh
#
# term - my terminal of choice
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

# execute alacritty if installed
command -v alacritty 2>/dev/null >&2 && \
    exec alacritty

exec xterm
