#!/bin/sh
#
# timeleft -- calculate time remaining on mpd playlist, not including finished songs
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

mpc playlist -f '%time%' | \
    sed "1,$(($(mpc status | awk -F'[#/]' '/paused|playing/ { print $2 }')-1))d" | \
    tr ':' ' ' | awk \
    '
        BEGIN { i = 0 }
        { i += $1 * 60 + $2 }
        END {
            if (int(i/3600) > 0)
                #print int(i/3600) "h " int((i%3600)/60) "m " int(i%60) "s"
                print int(i/3600) "h " int((i%3600)/60) "m"
            else if (int(i) > 0)
                #print int((i%3600)/60) "m " int(i%60) "s"
                print int((i%3600)/60) "m"
            else
                print "(empty)"
        }
    '
