#!/bin/sh
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

case "$(acpi -b)" in
    *Charging*) sudo tlp setcharge 90 1 BAT0 ;;
    *Not*charging*) sudo tlp setcharge 90 0 BAT0 ;;
esac
