#!/usr/bin/env bash
#
# tre - tree in pure bash

[[ -d $1 ]] && cd "$1" &>/dev/null

shopt -s globstar nullglob
printf '%s\n' "${PWD##*/}/"

for item in **; do
    [[ -d $item ]] && dir=/ || dir=

    nest=${item//[^\/]}
    item=${item//[^[:print:]]/^[}

    if [[ -d "${item}" ]]; then
        printf ' %s\e[1;34m%s\n\e[0m' "${nest//\//│  }├── " "${item##*/}${dir}"
    else
        printf ' %s\n' "${nest//\//│  }├── ${item##*/}${dir}"
    fi
done

printf ' └%s\b┘\n' "${nest//\//──┴}"
