#!/bin/sh
#
# wal - my version of Dylan's wal script :P
# (c) Kied Llaentenn (@kiedtl)
# See the LICENSE for more information.

main() {
	[ ! -f "${1}" ] && exit 1

	convert "${1}" -unique-colors -depth 16 txt:-
}

main "$@"
