#!/bin/sh
#
# wfi - Connect to Wi-Fi
# Create configuration with the following command:
# wpa_passphrase NETWORK P@S$W0rD1234 | tee /etc/wpa_supplicant.conf
# by Kied Llaentenn (@kiedtl)

INTERFACE=$(interface)
INTERFACE=${INTERFACE:-wlan0}

main() {
	pkill wpa_supplicant
    pkill dhcpcd
	ip l set $INTERFACE up
	wpa_supplicant -Bc /etc/wpa_supplicant/wpa_supplicant.conf -i $INTERFACE
	dhcpcd
}

main "$@"
