#!/usr/bin/env bash
#
# wfi - Connect to Wi-Fi
# Create configuration with the following command:
# sudo wpa_passphrase NETWORK P@S$W0rD1234 | sudo tee /etc/wpa_supplicant.conf

INTERFACE=wlan0

main() {
	sudo ip l set $INTERFACE up
	sudo wpa_supplicant -B -c /etc/wpa_supplicant.conf -i $INTERFACE
	sudo dhcpcd
}

main "$@"
