#!/bin/sh
#
# mkc - create wal colorscheme
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

case "$1" in
    p*)
        paleta ~/etc/colors/peaceful
        16

        colors=
        for i in 0 1 2 3 4 5 6 7
        do
            colors="$colors $(colorpicker -qod)"
        done

        echo $colors $colors
        ;;
    w*)
        shift
        cat <<EOF
{
    "wallpaper": "",
    "alpha": "100",
    "special": {
        "background": "$2",
        "foreground": "$1",
        "cursor": "$3"
    },
    "colors": {
        "color0": "$4",
        "color1": "$5",
        "color2": "$6",
        "color3": "$7",
        "color4": "$8",
        "color5": "$9",
EOF
        shift 9
        cat <<EOF
        "color6": "$1",
        "color7": "$2",
        "color8": "$3",
        "color9": "$4",
        "color10": "$5",
        "color11": "$6",
        "color12": "$7",
        "color13": "$8",
        "color14": "$9",
EOF
        shift 9
        cat <<EOF
        "color15": "$1"
    }
}

EOF
    ;;
esac
