#!/bin/sh
#
# ndmen: dmenu wrapper with better defaults
# usage: ndmen [FILE] [SHELL] [W] [H] [X] [Y]
#       FILE  default: dmenu_path
#       SHELL default: /bin/sh
#    example:
#       ndmen /etc/some_file /bin/cat
#
# (c) Kied Llaentenn
# see the COPYING file for more info.

. ~/.cache/wal/colors.sh

set -- $(res '$width $height') "$@"

w=$1	#w=$(echo "$1 / 1.75" | bc)
x=0	#x=$(( $1 / 2 - $w / 2 ))
	#y=$(( $2 / 5 ))
	#h=$(( $2 / 50 ))
shift 2

[ -z "$1" ] && p="dmenu_path"
[ -f "$1" ] && p="cat $1"

[ -z "$2" ] && s="${SHELL:-"/bin/sh"}" \
	|| s="cat"

${p} | dmenu -nb "$color0" -nf "$color15" -sb "$color15" -sf "$color0" \
	-p '$ ' -fn 'gomme:size=16' -l "${4:-$h}" -x "${5:-$x}" \
	-y "${6:-$y}" -wi "${3:-$w}" | "${s}" &
