#!/bin/bash
#
# rcmen: menu when right click
# from r/unixporn: "[dwm] plan 9 feel" by u/_viz_
# edited by kiedtl:
# 	- changed hacksaw to crud
#	- BPX/BCOL make static
#	- add clear function
#	- changed crud to xrectsel
# NOTE: requires bash due to use of arrays.

. ~/.cache/wal/colors.sh

reshape() {
    id=$(xdotool selectwindow)
    #eval $(crud)
    read -r W H X Y <<< $(xrectsel '%w %h %x %y')

    xdotool windowsize ${id} ${W} ${H}
    xdotool windowmove ${id} ${X} ${Y}
}

move() {
	id=$(xdotool getactivewindow)
	read -r _id oX oY oW oH <<< $(xdotool getwindowgeometry $id | \
		awk '{ print $2 }' | tr '\n,x' '   ')
	read -r X Y _ _ <<< $(xrectmov $oX $oY $oW $oH)

	xdotool windowmove ${id} ${X} ${Y}
}

new() {
    fw=9	# width of term font
    fh=18	# height of term font
    ib=24	# size of term inner border
    ob=3	# size of term windows WM border

    read -r W H X Y <<< $(xrectsel '%w %h %x %y') 
    w=$(( ( W - (ib + ob)*2 ) / fw ))
    h=$(( ( H - (ib + ob)*2 ) / fh )) 
    
    [ "$W" ] && st -g "${w}x${h}+${X}+${Y}"
}

delete() {
    id=$(xdotool selectwindow)
    xdotool windowclose ${id}
}

spawn() {
    #eval $(xdotool getmouselocation --shell)
    #9menu -geometry 10x10+24+47 -popup -warp \
	  #-bg "$color0" -fg "$color15" \
          #'new: echo new' 'delete: echo delete' 'move: echo move' 'resize: echo resize'
    ndmen 'echo -e new\nmove\nreshape\ndelete' 'cat'
}

$(spawn)
exit
