#!/bin/sh -e
#
# http://github.com/mitchweaver/bin
#
# grab a pape from unsplash and rice it
#
# with no search terms provided, it is random
#

dir=/tmp/pape
file=$dir/$$-pape.png
mkdir -p $dir

usage() { >&2 echo 'Usage: pape [-s] [-r] <search term>' ; exit 1 ; }

while [ "$1" ] ; do
    case $1 in
        -r)
            rice=true
            shift
            ;;
        -s)
            cp -fv $dir/last_pape.jpg ~/${file##*/}
            exit
            ;;
        -h)
            usage
            ;;
         *)
             url=http://source.unsplash.com/2400x1600/?$(echo $@ | tr ' ' ',')
             break
    esac
done

curl -L -# -C - -o $file --url ${url:-http://source.unsplash.com/random/2400x1600}
convert $file ${file%png}jpg
rm $file
file=${file%png}jpg
echo "$file"
feh "$file"

