#!/bin/bash
#
# scr: take a screenshot.
# (c) Dylan Araps

scr_dir=~/img/screenshots

# Give time for the dmenu window to go away...
sleep 0.5

printf -v date '%(%F)T' -1
printf -v time '%(%I-%M-%S)T' -1

mkdir -p "${scr_dir}/${date}"
scr=${scr_dir}/${date}/${date}-${time}

#import -window root "$scr".png
import "$scr".png
cp -f "$scr".png "${scr_dir}/current.png"

[ -z "$1" ] || up f "${scr_dir}/current.png"
xclip -selection clipboard -target image/png -i < "${scr_dir}/current.png"
