#!/bin/sh
#
# wifimen - wifi menu with dmenu
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

. $(which std)
INTERFACE=$(interface)

get_ssid_list() {
    sudo wpa_cli list_networks | tr '\t' ':' | cut -d: -f1,2,4 | \
        grep -Ev '(network id)|(Selected)' | \
        sed -e 's/\[CURRENT]/(current)/' -e 's/\[DISABLED]//' | \
        column -s: -to"            "
}

choose_ssid() {
    get_ssid_list | ndmen 'cat -' 'cat' | cut -f1 -d' '
}

pgrep wpa_supplicant >/dev/null || (
    sudo d sv restart wpa_supplicant || (
        herbe "wifimen: could not start wpa_supplicant"
        exit 1
    )
)

pgrep dhcpcd >/dev/null || (
    sudo d sv restart dhcpcd || (
        herbe "wifimen: could not start dhcpcd"
        exit 1
    )
)

option_a="select"

option_b=""
if [ $(cat "/sys/class/net/${INTERFACE}/operstate") = "up" ]
then
    option_b="reassociate"
fi

option_c=""
if [ $(cat "/sys/class/net/${INTERFACE}/operstate") = "up" ]
then
    option_c="disconnect"
fi

chosen=$(echo "$option_a\n$option_b\n$option_c" | ndmen 'cat -' 'cat' || exit 1)
case "$chosen" in
    select) sudo wpa_cli select_network $(choose_ssid || exit 1) ;;
    disconnect) sudo wpa_cli disconnect ;;
    reconnect) sudo wpi_cli reconnect ;;
    reassociate) sudo wpi_cli reassociate ;;
esac
