#!/bin/bash
#
# rcmen: menu when right click
# from r/unixporn: "[dwm] plan 9 feel" by u/_viz_
# edited by kiedtl:
# 	- changed hacksaw to crud
#	- BPX/BCOL make static
#	- add clear function
#	- changed crud to xrectsel
# NOTE: requires bash due to use of arrays.

. ~/.cache/wal/colors.sh

get_id_interactive() {
    xid=`xwininfo | grep 'Window id: '`
    echo ${xid} | cut -d':' -f3 | cut -d' ' -f2
}

resize() {
    id=`get_id_interactive`
    #eval $(crud)
    read -r W H X Y <<< $(xrectsel '%w %h %x %y')

    xdotool windowsize ${id} ${W} ${H}
    xdotool windowmove ${id} ${X} ${Y}
}

move() {
	id=$(get_id_interactive)
	read -r W H X Y <<< $(xrectsel '%w %h %x %y')

	xdotool windowmove ${id} ${X} ${Y}
}

new() {
    fw=9	# width of term font
    fh=15	# height of term font
    ib=16	# size of term inner border
    ob=4	# size of term windows WM border

    read -r W H X Y <<< $(xrectsel '%w %h %x %y') 
    w=$(( ( W - (ib + ob)*2 ) / fw ))
    h=$(( ( H - (ib + ob)*2 ) / fh )) 
    
    xterm -title terminal -geometry "${w}x${h}+${X}+${Y}"
}

delete() {
    id=`get_id_interactive`
    xdotool windowclose ${id}
}

spawn() {
    eval $(xdotool getmouselocation --shell)
    9menu -geometry 100x100+${X}+${Y} -popup \
	  -bg "$color7" -fg "$color0" \
          'new: echo new' 'delete: echo delete' 'move: echo move' 'resize: echo resize'
}

$(spawn)
exit
