#!/bin/sh
#
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING file for copyright information.

command=$@

read items
set -- $items

if [ $# -lt 2 ]
then
    echo "$@"
    exit 0
fi

accm=$($command "$1" "$2")
shift 2

exec echo "$accm" $@ | $0 $command
