#!/bin/sh
#
# up - text/file upload
# (c) Kiëd Llaentenn <kiedtl@tilde.team>
# See the COPYING for more information.

usage() {
		echo "up - text/file upload
(c) Kiëd Llaentenn

USAGE:
    $ up [f|t|i|h] [args]

OPTIONS:
    f   [file]  post file to 0x0.st
    t   [file]  post text from file to ix.io
    i           post text from stdin to ix.io
"
}

upload() {
    output=$(curl -s -F"file=@${1}" 0x0.st)
    qrencode -m 2 -s 2 -t ansiutf8 -o - "$output"
    printf '%s\n' "$output"
}

main() {
	case "$1" in
		f*) upload "$2" ;; # post file
		t*) cat "$2" | curl -F 'f:1=<-' ix.io ;; # post text from file
		i*) curl -iF 'f:1=<-' ix.io ;; # stdin
		 *) usage ;;
	esac
}

main "$@"

