#!/bin/sh
#
# wfi - Connect to Wi-Fi
# Create configuration with the following command:
# wpa_passphrase NETWORK P@S$W0rD1234 | tee /etc/wpa_supplicant.conf
# by Kied Llaentenn (@kiedtl)
#
# TODO: ethernet

INTERFACE=$(interface)
INTERFACE=${INTERFACE:-wlan0}

dhcp() {
    if has dhcpcd; then
        pkill dhcpcd ; dhcpcd
    elif has udhcpc; then
        pkill udhcpc ; udhcpc -i "$INTERFACE"
    fi
}

wifi() {
    ip l set $INTERFACE up
    pkill wpa_supplicant ; wpa_supplicant -B \
        -c /etc/wpa_supplicant/wpa_supplicant.conf \
        -i $INTERFACE
    sleep 1
    dhcp
}

wifi "$@"
