#!/bin/mksh
#
# wfi - Connect to Wi-Fi
# Create configuration with the following command:
# wpa_passphrase NETWORK P@S$W0rD1234 | tee /etc/wpa_supplicant.conf
# by Kied Llaentenn (@kiedtl)
#
# TODO: ethernet

INTERFACE=$(interface)
INTERFACE=${INTERFACE:-wlan0}

dhcp() {
    if has dhcpcd; then
        doas pkill dhcpcd ; doas dhcpcd
    elif has udhcpc; then
        doas pkill udhcpc ; doas udhcpc -i "$INTERFACE"
    fi
}

wifi() {
    doas ip l set $INTERFACE up
    doas pkill wpa_supplicant ; doas wpa_supplicant -B \
        -c /etc/wpa_supplicant/wpa_supplicant.conf \
        -i $INTERFACE
    sleep 1
    dhcp
}

wifi "$@"
